src/reporter.cc
closes #10 
I'm using appoptics-apm-node to send my metrics, but when I used the TAGs I realized that the values ​​of the keys are coming with the value of the TAGs.
To reproduce the problem, I created a simple application and attached below, you need to run specifying your appoptics service key
[appoptics-bindings-node-tags-bug.zip](https://github.com/appoptics/appoptics-bindings-node/files/3169370/appoptics-bindings-node-tags-bug.zip)
```shell
npm install
APPOPTICS_SERVICE_KEY={YOUR-SERVICE-KEY} npm start
```
Looking for at the code I realized that in the assignment of the TAGs the same object, the values ​​of the TAGs, was being passed to key and value, probably error by CTRL+C and CTRL+V
The hotfix is here, but I could not run the tests :disappointed:
=> HOTFIX - Reporter.sendMetric is sending the keys name as the value

src/reporter.cc
- it's useful to know the error code when oboe_span() and oboe_http_span() fail.
- previously returned null string
=> src/reporter.cc - return code on error

.npmignore, CONTRIBUTING.md, bench/metadata.bench.js, binding.gyp, index.js, package.json, src/metrics/eventloop.cc, src/metrics/eventloop.h, src/metrics/gc.cc, src/metrics/gc.h, src/metrics/hdr_histogram.h, src/metrics/metrics.cc, src/metrics/process.cc, src/metrics/process.h, src/reporter.cc, test/metadata.test.js, test/reporter-metrics-memory.test.js, test/reporter-metrics.test.js, test/reporter.test.js, test/settings.test.js
- new function send_metrics_core() - used by new sendMetrics() and legacy sendMetric()
- new test/reporter-metrics-memory.test.js file because memory loss tests are relatively slow
- new test/reporter-metrics.test.js to send sendMetrics() call.
- eslint conformance
=> Metrics array

package.json
- requires that the repo secrets:
PROD_AWS_ACCESS_KEY_ID
PROD_AWS_SECRET_ACCESS_KEY
be updated
=> 11.0.0-rc2

package.json
I think the intention of these lambda version suffixes is to reset to 1 for each agent/bindings version, and only increment if we needed to release a new lambda layer off of the same agent/bindings version.
The current GA lambda layer:
> description: apm v9.1.0-lambda-2, bindings v10.0.0-lambda-1, auto v1.0.0-lambda-1
The RC lambda layer versions will be:
> description: apm v10.0.1-lambda-1, bindings v11.0.0-lambda-1, auto v1.0.0
=> AO-19439 lambda version

.github/docker-node/10-alpine3.9-build.Dockerfile, .github/docker-node/10-amazonlinux2.Dockerfile, .github/docker-node/10-centos7-build.Dockerfile, .github/docker-node/10-centos7.Dockerfile, .github/docker-node/10-centos8.Dockerfile, .github/docker-node/12-alpine3.9-build.Dockerfile, .github/docker-node/12-amazonlinux2.Dockerfile, .github/docker-node/12-centos7-build.Dockerfile, .github/docker-node/12-centos7.Dockerfile, .github/docker-node/12-centos8.Dockerfile, .github/docker-node/14-alpine3.10-build.Dockerfile, .github/docker-node/14-amazonlinux2.Dockerfile, .github/docker-node/14-centos7-build.Dockerfile, .github/docker-node/14-centos7.Dockerfile, .github/docker-node/14-centos8.Dockerfile, .github/docker-node/nvm-v0.38.0-install.sh
This Pull Request is the **2nd** in a series of Pull Requests to refactor GitHub Actions.
The single commit (5cf787fcc796a84ef6bb286206938f70967c5744) added a directory under the .github (hidden) directory that houses dockerfiles and any additional files that may be bundled into images. 
Files currently included:
- 15 dockerfiles. 6 used in the build process. 9 used for testing.
- A recent nvm install script used by some of the images.
This setup will be used to build node images and publish them to github package so that they can later be used by github workflows. 
Dockerfile notes:
- Image defined by each file is intended to be the minimal required to fulfill it's task. Definitions have been "trimmed" from both their original setup and the one used for the prototype in [Pull Request …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-2

.github/docker-node/14-centos8.Dockerfile, .github/workflows/docker-node.yml
This Pull Request is the **3rd** in a series of Pull Requests to refactor GitHub Actions.
The first commit (d83014866a74c581cb89edb741cd86fb1c36f35a) added a workflow that builds and publishes images to GitHub Container Registry (ghcr.io). Images are scoped to repo and tagged.
When run, the workflow creates a ["single" package](https://github.com/orgs/appoptics/packages) named `node` scoped to `appoptics/appoptics-bindings-node` (the repo). Package has [multiple tagged images](https://github.com/appoptics/appoptics-bindings-node/pkgs/container/appoptics-bindings-node%2Fnode) for each of the dockerfiles from which it was built. For example, the image created from a file named `10-centos7-build.Dockerfile` has a `10-centos7-build` tag and can pulled from …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-3

.github/workflows/push.yml
This Pull Request is the **4th** in a series of Pull Requests to refactor GitHub Actions.
The single commit (b0d6d26b974971419b5f4790aa82751a52c92470) added a workflow used for development.
Usage:
* Push to master is disabled by branch protection.
* Push to branch will trigger push.yml. 
* Workflow will:
- Build the code pushed on the runner with node 14 (latest currently supported).
- Run the tests against the build.
* Workflow simply confirms code is not "broken".
* Manual trigger supported. Enables to select version number (e.g. `10.16.0`) to build code on.
Diagram:
```
push to branch ──► ┌───────────────────┐ ─► ─► ─► ─► ─►
│Single Build & Test│ contained build
manual (image?) ─► └───────────────────┘ ◄── ◄── ◄── ◄──
```
Todos:
1. Update default node version to 16 when support is …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-4

.github/config/build-group.json, .github/config/docker-node.json, .github/config/fallback-group.json, .github/config/prebuilt-group.json, .github/scripts/matrix-from-json.sh, .github/workflows/accept.yml, .github/workflows/docker-node.yml, .github/workflows/review.yml
This Pull Request is the **6th** in a series of Pull Requests to refactor GitHub Actions (AO-20081). 
It introduces **the main workflow** of this refactor - Accept which runs when a pull request is merged.
Overview:
The npm package in this repo is `node-pre-gyp` enabled and is published using in a two step process. First prebuilt add-on tarballs are uploaded to an S3 bucket, and then an NPM package is published to the NPM registry. Prebuilt tarballs must be versioned with the same version as the NPM package and they must be present in the S3 bucket prior to the NPM package itself being published to the registry. There are many platforms that can use the prebuilt add-on but will fail to build it, hence the importance of the prebuilts.
Definitions:
* Build Group are images on which the …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-6

.github/config/target-group.json, .github/workflows/docker-node.yml, .github/workflows/release.yml
This Pull Request is the **7th** in a series of Pull Requests to refactor GitHub Actions (AO-20081). 
It adds a release workflow that is `npm` and `git` triggered, using npm builtin `version` command and `git push tag`. No github hooks needed.
Definitions:
* Build Group are images on which the various versions of the add-on are built. They include combinations to support different Node versions and libc implementations. Generally build is done with the lowest versions of the OS supported, so that `glibc`/`musl` versions are the oldest/most compatible.
* Target Group images include a wide variety of OS and Node version combinations. Group includes both images that can build from code as well as those which can not.
Usage:
* To Release:
1. On branch run `npm version …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-7

.github/workflows/accept.yml, .github/workflows/docker-node.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/review.yml, package-lock.json, package.json, test/expose-gc/init-memory.test.js
This Pull Request is the **8th** and **last** in a series of Pull Requests to refactor GitHub Actions (AO-20081). 
Wrapping things up by increasing timeout on flaky test (35f511e6e1394d600ab79ad366f60d1514552409), renaming the workflows to better display in GitHub Actions sidebar (698dab1e2ae2b4a30dd2b146ca3eae2625b0facc) and adding a way to designate a branch so that it would not trigger a build on push (698dab1e2ae2b4a30dd2b146ca3eae2625b0facc). Main use case for latter is GitHub online documentation editor commits. No other filtering scheme works as planned.
Onwards.
P.S - Multiple feature branches, draft PRs,  rebasing, pushing with --force-with-lease. Github seems very excited logging things below... ignore...
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-8

.github/config/build-group.json, .github/config/docker-node.json, .github/config/fallback-group.json, .github/config/prebuilt-group.json, .github/config/target-group.json, .github/docker-node/14-alpine3.10-build.Dockerfile, .github/docker-node/14-alpine3.9-build.Dockerfile, .github/docker-node/14-alpine3.9.Dockerfile, .github/docker-node/16-alpine3.10.Dockerfile, .github/docker-node/16-alpine3.11-build.Dockerfile, .github/docker-node/16-alpine3.9-build.Dockerfile, .github/docker-node/16-alpine3.9.Dockerfile, .github/docker-node/16-amazonlinux2.Dockerfile, .github/docker-node/16-centos7-build.Dockerfile, .github/docker-node/16-centos7.Dockerfile, .github/docker-node/16-centos8.Dockerfile, .github/docker-node/docker-entrypoint.sh, .github/workflows/accept.yml, .github/workflows/release.yml, .github/workflows/review.yml
This Pull Request adds support for Node 16 by:
1. Adding the Dockerfiles (be4c3a6e197dbb958bf83b8edfa74644df3c93f3) (image build has been triggered manually)
2. Adding resulting images to config groups (96198d90904530205baf2e5697cdb31fdb703360)
3. Modifying matrix/container workflows to allow npm install (cea153172649e6100919dfa670cc85c9911041b9).
Support for Node 16 required two adjustments over previous versions:
1. Node moved to [c++14](https://github.com/nodejs/node/commit/f9d6de41a7cb7e512eab4e8ed9b9a5dbfbac11e2#diff-9513a0c08584f4800e1461ca8c3456d1aeb899968ea14b2f6859ea462c37b5bb) which does not compile on Centos 7 "out of the box" (but does on Centos 8).
Centos 7 comes with:
- gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
- glibc-2.17-324.el7_9.x86_64
Centos 8 comes with:
- gcc (GCC) …
=> AO-20084-Enable-Support-for-Node-16

setup-liboboe.js
This Pull Request modifies `setup-liboboe.js`.
It:
- Removes outdated email address and some decoration from liboboe's platform warning message (2754a9f)
- Removes commented-out code (2170016)
- Removes dead-code reference to alpineLibreSSL (9ce36b2)
Build check/tests pass.
Note that `package.josn` has an `os` setting:
```
"os": [
"!darwin",
"!win32"
],
```
And will in most cases (all?) halt install/rebuild before setup-liboboe.js is invoked
=> AO-20163-Remove-Outdated-Support-Email-Address

package-lock.json, package.json
The pull request removes outdated `node-gyp` from dependency list. 
`node-gyp` comes with [npm](https://docs.npmjs.com/cli/v6/commands/npm#dependencies). When not specified as a dependency, the version that comes with npm will be used.
```
Node: v10.24.1
NPM: 6.14.12
using node-gyp@5.1.0
Node v12.22.3
NPM 6.14.13
using node-gyp@5.1.0
Node v14.17.3
NPM 6.14.13
using node-gyp@5.1.0
Node v16.5.0
NPM: 7.19.1
using node-gyp@7.1.2
```
=> AO-19333-Update-Node-Gyp-Version

.github/docker-node/12-amazonlinux2.Dockerfile, .github/docker-node/12-centos7-build.Dockerfile, .github/docker-node/12-centos7.Dockerfile, .github/docker-node/12-centos8.Dockerfile, .github/docker-node/14-alpine3.9-build.Dockerfile, .github/docker-node/14-alpine3.9.Dockerfile, .github/docker-node/14-amazonlinux2.Dockerfile, .github/docker-node/14-centos7-build.Dockerfile, .github/docker-node/14-centos7.Dockerfile, .github/docker-node/14-centos8.Dockerfile, .github/docker-node/16-alpine3.10.Dockerfile, .github/docker-node/16-alpine3.9-build.Dockerfile, .github/docker-node/16-alpine3.9.Dockerfile, .github/docker-node/16-amazonlinux2.Dockerfile, .github/docker-node/16-centos7-build.Dockerfile, .github/docker-node/16-centos7.Dockerfile, .github/docker-node/16-centos8.Dockerfile, .github/workflows/accept.yml, .github/workflows/docker-node.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/review.yml, dev/Dockerfile, package-lock.json, package.json
This is a maintenance pull request for GitHub Actions.
1. Commit c445469 removes a TODO from the Prep workflow (docker-node.yml). The workflow is triggered by a push of a Dockerfile. Hence it has already [ran successfully](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1143814102) on commits in this Pull Request (and is also listed as part of the ["checks"](https://github.com/appoptics/appoptics-bindings-node/pull/71/checks) for this PR)
2. Commit 7403646 updates all other workflow so that all jobs have a name and spacing is consistent. There is *no* functionality change.
3. Commit 981de93 changes branch ending silencing GitHub push action to `-no-action` (replaced `-no-build`). This matches what will be used in downstream repo.
4. A series of commits upgrades …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-9

.github/README.md, README.md
This Pull Request consolidates documentation into a single README document.
The README is placed inside .`github` directory. This takes advantage of an undocumented GitHub behavior where README files in the `.github` directory override the default README when viewed on GitHub. The "hack" allows us to have this long document (aimed at developers) as default on GitHub, and a much simpler README at npm (aimed at end users).
Single commit is result of rebasing multiple online editing commits. Branch stays open for further iterations. Feel free to participate.
=> AO-20192-Update-Documentation

.github/README.md, .github/workflows/release.yml, dev/repo/package-patch.js
This pull-request changes the git tag used to trigger the Release workflow from `alpha` to `prerelease`.
Moving fwd:
- Version promotion will be done with: `npm version prerelease --preid prerelease`.
- Resulting in `"version": "11.0.1-prerelease.1"` in `package.json`. 
- Will be npm tagged `prerelease`. 
- Will generate binaries with name` apm_bindings-v11.0.1-prerelease.1-node-v72-napi-v7-glibc-x64.tar.gz`.
Dev Release result:
- https://github.com/appoptics/appoptics-bindings-node-dev/actions/runs/1199350265
- https://www.npmjs.com/package/@appoptics/apm-binding-dev
- Note: dev package is also tagged `latest` as it is the only version of the package present. For packages with history, the only tag will be `prerelease`.
Also note - the dev repo readme is the full version (from `.github` …
=> AO-20081-Refactor-GitHub-Actions-Test-Publish-Workflows-10

.github/README.md, package-lock.json, package.json
Prerelease run with accumulated documentation updates.
Note: 
We've decided that "packages maintainers may release as many prerelease versions as they deem appropriate" without need for SolarWinds approval.
Merging this pull request does not trigger the prerelease.
The trigger is by git tag push that will come after all workflows pass..
Future prereleases will not contain such message.
=> 11.0.1-prerelease.0

.github/config/fallback-group.json, .github/config/prebuilt-group.json
This Pull Request moves `node:16-stretch` from Fallback Group to Prebuilt Group. 
Image can not build due Node 16 upgrading to node-gyp@8 which requires Python 3.6 which does not ship with Debian 9 Stretch (has 3.5). 
This is a permanent change.
Reference:
* NPM issue and discussion pointers: https://github.com/npm/run-script/issues/40
* NPM not reverting to node-gyp@7: https://github.com/npm/run-script/pull/41
* node-gyp not reverting python 3.5: https://github.com/nodejs/node-gyp/issues/2540
Workflow passes: https://github.com/appoptics/appoptics-bindings-node/actions/runs/1413186370
=> AO-20626-Workflows-Halt-Due-to-Fallback-Group-Install

src/settings.cc
This Pull request added oboe_metadata_init call before calling oboe_metadata_fromstr as required by liboboe api.
All tests pass.
=> Fix-oboe_metadata_fromstr-Call

.github/scripts/liboboe-checksum.sh, .github/workflows/accept.yml, .github/workflows/release.yml, .github/workflows/review.yml, dev/env.sh, dev/oboe.sh, package.json
This pull request adds a chucksum step to Accept and Release workflows. It ensures that the binaries in the repo match the binaries published to the bucket.
Commit (97a41d70520a028cdd4261b1fb79de3e14f6fb72) added script to checksum oboe binaries against sha256 files downloaded for current version from https://files.appoptics.com/c-lib.
Commit (87960477921af850f0237761c575a47eb2c82e2f) Modified Accept and Release workflows to perform checksum as part of first job (loading data). Workflow will err and stop if checksum do not match.
Commit (87960477921af850f0237761c575a47eb2c82e2f) Modified the Review workflow to perform checksum as a step at the end of the workflow. Workflow will err and stop if checksum do not match but only after building and testing.
If binaries are replaced the …
=> AO-20476-liboboe-Checksum

package-lock.json, package.json
This Pull Request updates minor and patch versions of dependencies:
- @mapbox/node-pre-gyp to 1.0.7 (latest) 
- nan to 2.15.0  (latest)
[All Review tests pass](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1517442048)
[All Acceptance test pass](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1517572445)
Note: flaky memory tests with Centos and Node 16/17 in pre-pass runs.
=> AO-20733-Upgrade-Dependencies-Minor-Patch-Version

package.json
This pull request sets `node-pre-gyp` to only build one set of binaries using Node API version 4.
According to [Node-API version matrix](https://nodejs.org/api/n-api.html#node-api-version-matrix):
> Node-API versions are *additive* and versioned independently from Node.js. Version 4 is an extension to version 3 in that it has all of the APIs from version 3 with some additions. This means that it is *not necessary to recompile for new versions of Node.js which are listed as supporting a later version*.
NAPI 4 is good for everything from Node v10.16.0 and above.
A January commit added NAPI 7 to the build versions: https://github.com/appoptics/appoptics-bindings-node/commit/c443f6454533123c8745fc51b3c927bd6ae16dde Since then we have been building and distributing a double set of binaries. …
=> AO-20749-build-NAPI-4-Only

test/event-to-string.test.js
This pull request adds test coverage to the Event toString method which supports various formatted outputs.
Formatting functionality was added to bindings in https://github.com/appoptics/appoptics-bindings-node/commit/dd6556b2dd20c2a183f6d2adca538850eb099745 and has been untested since.
Functionality will be modified for https://github.com/appoptics/appoptics-bindings-node/tree/oboe-10.3.0 hence test coverage is required on master branch.
Tests that run on branch include [added tests](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1547908187). All tests pass.
=> AO-20757-Test-Coverage-for-Event.toString

.github/README.md, dev/oboe.sh, package.json
This pull request changes the staging bucket used to store prebuilt binaries and obtain liboboe.
Bucket is now `solarwinds-apm-staging.s3-us-west-2.amazonaws.com`
Since 10.3.0 is still staged, the Accept Workflow that builds binaries and places them in the staging bucket, will halt due to liboboe not passing a production checksum.
Pull Request was tested using the dev repo with checksum protection disabled.
[Build succeeded](https://github.com/appoptics/appoptics-bindings-node-dev/actions/runs/1551534614).
- Pull Request merges into oboe-10.3.0 branch.
- [Last Review check](https://github.com/appoptics/appoptics-bindings-node/runs/4453420720?check_suite_focus=true) is a liboboe checksum. It fails, by design, as 10.3.0 is still staged.
=> NH-5263-Store-Prebuilt-Staging-Binaries-at-solarwinds-apm-staging

src/event/event-to-string.cc, test/event-to-string-mode-0.test.js, test/event-to-string-mode-1.test.js
This pull request adds mode 1 (traceparent) support to the Event toString method which can generate various formatted outputs. Tests for both mode 0 and mode 1 are included. Support for outdated versions of oboe metadata have been removed.
Formatting functionality was added to bindings in https://github.com/appoptics/appoptics-bindings-node/commit/dd6556b2dd20c2a183f6d2adca538850eb099745 and tests (for xtrace) were added in https://github.com/appoptics/appoptics-bindings-node/commit/4d15d8512c9d53a925e457bc17d40bbbbf478a73.
- Pull Request merges into oboe-10.3.0 branch.
- Tests that run on branch include [added tests](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1552715261).
- [Last Review check](https://github.com/appoptics/appoptics-bindings-node/runs/4453431725?chec …
=> NH-5266-Adapt-Event.toString-functionality

package-lock.json, package.json
This Pull Request updates major version of node-addon-api to 4.2.0 (latest) from 2.0.0.
[All Review tests pass](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1559576797)
[All Acceptance test pass](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1557525737)
=> AO-20736-Upgrade-node-addon-api-to-latest

test/sanitizer.test.js
This pull request adds test coverage to the Sanitizer functionality used to remove details from SQL queries.
Sanitization was added to the bindings in the first commit https://github.com/appoptics/appoptics-bindings-node/commit/d82692bb8d57b106114dbac7f4efc878054fc214. It is an FSM written in C++ and has been untested since.
Test coverage is based on the [Ruby Agent test coverage](https://github.com/appoptics/appoptics-apm-ruby/blob/c36bd5b597cb37beeb39c2e7fa302efb3ad49d13/test/support/sql_sanitize_test.rb). The implementation differ.
Tests that run on branch include [added tests](https://github.com/appoptics/appoptics-bindings-node/actions/runs/1560645295
). All tests pass.
=> AO-20750-Test-Coverage-for-Sanitizer

src/settings.cc
This pull request fixes an issue causing oboe to log errors (and then gracefully proceed) during normal operation.
When a request comes in without an x-trace header (which would be the majority of requests) the agent passes an object to the bindings. When there is no incoming x-trace, the object has an empty string in the xtrace key. The bindings then act on the xtrace value accordingly. However, when a data struct is sent to to oboe to make the tracing decision, x-trace is always set to a string. Thus, when it is an empty string, oboe will log an error.
`[Fri Mar 25 23:36:51 2022] oboe_sample_layer: passed in x-trace seems invalid, ignoring [settings.c:948] [AppOptics-settings-low p#1.1]`
A conditional was added around the the value of xtrace in the struct sent to oboe for tracing …
=> AO-21079-Do-Not-Pass-xtrace-String-to-Oboe-when-Empty

.github/README.md, .github/workflows/accept.yml, .github/workflows/push.yml, .github/workflows/review.yml, package-lock.json, test/bindings.test.js, test/event-mode-1.test.js, test/event-to-string-mode-0.test.js, test/event-to-string-mode-1.test.js, test/expose-gc/reporter-metrics-memory.test.js, test/reporter-metrics.test.js, test/reporter.test.js, test/settings-mode-1.test.js
This pull request refactors the test and GitHub Actions setup so that they work with a duo of backends.
It is a change to the `oboe-10.3.0` branch corresponding the one made in #103 to the `master` branch.
1. Updated tests:
- Removed all hard coded urls.
- Removed use of private environment variables `AO_TOKEN_PROD` and `AO_TOKEN_STG`. Instead use new standard public environment variables `SW_APM_SERVICE_KEY`, `SW_APM_COLLECTOR` to set which servers test run against when in mode 1.
- Added `SW_TEST_PROD_SERVICE_KEY` environment variable to cover the specific test case of initialization without url in mode 1.
2. Updated GH Actions to set new environment variables as required by modified tests.
3. Updated documentation to reflect changes in tests and GH Action setup.
4. Ran `npm audit fix` …
=> NH-11002-Refactor-Tests-and-GH-Actions-for-Dual-Repo-and-Backends

package-lock.json, package.json, src/bindings.cc
This pull request updates the value of the [entry point](https://github.com/appoptics/appoptics-bindings-node/blob/b2ef9eb1732e14b846c339003141cbb8c807fe5a/src/bindings.cc#L299) for the bindings addon. 
Per documentation the entry point for the addon should match the target name used by node-gyp which in should match the module name used by node-pre-gyp. See: [1](https://nodejs.org/api/addons.html), [2](https://github.com/nodejs/node-addon-api/blob/main/doc/node-gyp.md).
The current value set for the [entry point](https://github.com/appoptics/appoptics-bindings-node/blob/master/src/bindings.cc#L299) does not match the value in used by [node-gyp](https://github.com/appoptics/appoptics-bindings-node/blob/master/binding.gyp#L3).
Though everything worked just fine with mismatched values - …
=> AO-21101-Change-NODE_API_MODULE-Macro-entry-point-Definition

.github/scripts/is-published.sh, .github/workflows/release.yml
This pull request updateds the GithHub Actions Release workflow so that it becomes "fail safe" and can be re-run without issues in case a failure happened during a previous run.
The bindings package is published in a two step process. First prebuilt add-on tarballs are uploaded to an S3 bucket using `node-pre-gyp`, and then an NPM package is published to the NPM . Prebuilt tarballs must be versioned with the same version as the NPM package and they must be present in the S3 bucket prior to the NPM package itself being published to the registry.
The process is automated using the Release workflow (https://github.com/appoptics/appoptics-bindings-node/tree/master/.github#release---push-version-tag) which, after the build and publish of the tarballs , also installs them on multiple operating …
=> AO-20470-Update-Release-Workflow-to-Make-it-Fail-Safe

package.json
The lambda implementation suffers form several issues (AO-19620, AO-19603, AO-19911, AO-20761) and thus serverless support would not initially ship for `solarwinds-apm`.
This pull request removes the version suffix used by lambda from package.json. All other lambda related functionality, added in #27, is left as-is.
- Pull Request merges into `nh-main` branch. Bindings built from `master` will stay unchanged.
=> NH-11306-Gracefully-Disable-Lambda-Functionality
